name: solid-structure

services:
  db:
    container_name: structure-db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: solid-gym
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
