name: Run e2e Tests

on: [pull_request]

jobs:
  run-unit-tests:
    name: e2e Test Job
    runs-on: ubuntu-latest

    services:
      postgresql:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: docker
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: solid-gym
          POSTGRESQL_HOST: postgresql

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..10}; do
            echo "Tentando conectar ao banco..."
            pg_isready -h 0.0.0.0 -p 5432 -U docker && break
            sleep 3
          done
        # - run: npm run test:e2e
        env:
          DATABASE_URL: "postgresql://docker:docker@postgresql:5432/solid-gym"
          POSTGRESQL_HOST: postgresql
          NODE_ENV: test
          JWT_SECRET_KEY: test
