name: Run e2e Tests 

on: [pull_request]

jobs:
  run-unit-tests:
    name: e2e Test Job
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env: 
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: solid-gym
          POSTGRESQL_DATA_DIR: /data/postgres
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Aguardando banco de dados..."
          until pg_isready -h localhost -p 5432; do
            sleep 1
          done
      - run: npm run test:e2e
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/solid-gym"
          NODE_ENV: test
          JWT_SECRET_KEY: test
     